---
substitutions:
  name: "craftroom_lightswitch"
  device_name: craftroom_lightswitch
  device_description: Craft Room Lightswitch
  friendly_name: Craft Room Lightswitch
  default_state: "RESTORE_DEFAULT_ON"
  device_format: EU
  gang_count: 1

<<: !include common/tx_ultimate_easy_common.yaml
