---
substitutions:
  name: "ensuite_lightswitch"
  device_name: ensuite_lightswitch
  device_description: Ensuite Lightswitch
  friendly_name: Ensuite Lightswitch
  default_state: "RESTORE_DEFAULT_ON"
  device_format: EU
  gang_count: 1

<<: !include common/tx_ultimate_easy_common.yaml
