---
substitutions:
  name: "ensuite_switch"
  device_name: ensuite_switch
  device_description: Ensuite Lightswitch
  friendly_name: Ensuite Switch
  default_state: "RESTORE_DEFAULT_ON"
  device_format: EU
  gang_count: 1

<<: !include common/tx_ultimate_easy_common.yaml
