---
substitutions:
  name: "guestbedroom_switch"
  device_name: guestbedroom_switch
  device_description: Guest Bedroom Lightswitch
  friendly_name: Guest Bedroom Switch
  default_state: "RESTORE_DEFAULT_ON"
  device_format: EU
  gang_count: 1

<<: !include common/tx_ultimate_easy_common.yaml
