---
substitutions:
  name: "hall_dual_switch"
  friendly_name: "Hall Dual Switch"
  device_description: "Hall Dual Light Switch"
  default_state: "RESTORE_DEFAULT_ON"
  device_format: EU
  gang_count: 2

<<: !include common/tx_ultimate_easy_common.yaml
