---
substitutions:
  name: "hall_single_switch"
  friendly_name: "Hall Single Switch"
  device_description: "Hall Single Light Switch"
  device_format: EU
  gang_count: 1

<<: !include common/tx_ultimate_easy_common.yaml
