---
substitutions:
  name: "hall_single_lightswitch"
  friendly_name: "Hall Single Lightswitch"
  device_description: "Hall Single Lightswitch"
  device_format: EU
  gang_count: 1

<<: !include common/tx_ultimate_easy_common.yaml
