---
substitutions:
  name: "kitchen_lightswitch"
  friendly_name: "Kitchen Lightswitch"
  device_description: "Kitchen Lightswitch"
  device_format: EU
  gang_count: 2

<<: !include common/tx_ultimate_easy_common.yaml
