---
substitutions:
  name: "kitchen_switch"
  friendly_name: "Kitchen Switch"
  device_description: "Kitchen Light Switch"
  device_format: EU
  gang_count: 2

<<: !include common/tx_ultimate_easy_common.yaml
