---
substitutions:
  name: "living_room_lightswitch"
  friendly_name: "Living Room Lightswitch"
  device_description: "Living Room Lightswitch"
  device_format: EU
  gang_count: 3

<<: !include common/tx_ultimate_easy_common.yaml
