---
substitutions:
  name: "living_room_switch"
  friendly_name: "Living Room Switch"
  device_description: "Living Room Light Switch"
  device_format: EU
  gang_count: 3

<<: !include common/tx_ultimate_easy_common.yaml
