---
packages:
  plug: !include common/localbytes_plug_pm_common.yaml
  common: !include common/power_plug_common.yaml

substitutions:
  device_name: hot_tap
  device_description: Hot Tap Power Plug
  friendly_name: Hot Tap Power Plug
  default_state: "RESTORE_DEFAULT_ON"
  main_icon: power-socket-uk
