---
packages:
  plug: !include common/localbytes_plug_pm_common.yaml
  common: !include common/power_plug_common.yaml

substitutions:
  device_name: tin_hut_it
  device_description: Tin Hut IT Power Plug
  friendly_name: Tin Hut IT Power Plug
  default_state: "RESTORE_DEFAULT_ON"
  main_icon: power-socket-uk
