---
substitutions:
  name: "study_lightswitch"
  friendly_name: "Study Lightswitch"
  device_description: "Study Lightswitch"
  device_format: EU
  gang_count: 1

<<: !include common/tx_ultimate_easy_common.yaml
