---
substitutions:
  name: "study_switch"
  friendly_name: "Study Switch"
  device_description: "Study Light Switch"
  device_format: EU
  gang_count: 1

<<: !include common/tx_ultimate_easy_common.yaml
